### ISSUE TITLE
Override a service

### ISSUE THREAD

**Issue by domarcio** [akrabat/rka-slim-zfsm-container#4]
Hi @akrabat 

The Service Manager from ZF2 does allow override a service: **A service by the name or alias "notFoundHandler" already exists and cannot be overridden, please use an alternate name**.

Is it possible to solve this ?

``` php
$container = new RKA\ZsmSlimContainer\Container($config);
$container['notFoundHandler'] = function ($container) {
    return function ($request, $response) use ($container) {
        return $container['response']
            ->withStatus(404)
            ->withHeader('Content-Type', 'text/html')
            ->write('Page not found');
    };
};
```

Regards

**Comment by garethellis36** [comment]
@marciovinicius I had the same problem [in this issue](https://github.com/akrabat/rka-slim-zfsm-container/issues/2). You can override by doing this:

``` php
$container->setAllowOverride(true);
```

**Comment by domarcio** [comment]
@garethellis36 Thank you for that! The problem is solved.
